-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.conteo_pasajeros
(
    total integer,
    tiempo time with time zone,
    id serial NOT NULL,
    CONSTRAINT conteo_pasajeros_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estacion
(
    id integer NOT NULL DEFAULT nextval('"estacion_ID_seq"'::regclass),
    nombre character varying(30) COLLATE pg_catalog."default",
    direccion character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT estacion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pasajero
(
    id integer NOT NULL DEFAULT nextval('"pasajero_ID_seq"'::regclass),
    nombre character varying(100) COLLATE pg_catalog."default",
    direccion_residencia character varying COLLATE pg_catalog."default",
    fecha_nacimiento date,
    CONSTRAINT pasajero_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.trayecto
(
    id integer NOT NULL DEFAULT nextval('"trayecto_ID_seq"'::regclass),
    id_tren integer,
    id_estacion integer,
    nombre character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT trayecto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tren
(
    id integer NOT NULL DEFAULT nextval('"tren_ID_seq"'::regclass),
    modelo character varying(30) COLLATE pg_catalog."default",
    capacidad integer,
    CONSTRAINT tren_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.viaje
(
    id integer NOT NULL DEFAULT nextval('"viaje_ID_seq"'::regclass),
    id_pasajero integer,
    id_trayecto integer,
    inicio date,
    fin date,
    CONSTRAINT viaje_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.trayecto
    ADD CONSTRAINT trayecto_estacion_fkey FOREIGN KEY (id_estacion)
    REFERENCES public.estacion (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.trayecto
    ADD CONSTRAINT trayecto_tren_fkey FOREIGN KEY (id_tren)
    REFERENCES public.tren (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT viaje_pasajero_fkey FOREIGN KEY (id_pasajero)
    REFERENCES public.pasajero (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.viaje
    ADD CONSTRAINT viaje_trayecto_fkey FOREIGN KEY (id_trayecto)
    REFERENCES public.trayecto (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;